name: DevSecOps CI Pipeline with Security Scan

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Run Hello Command
      run: echo "Hello, Uyi! Your CI Pipeline is working!"

    - name: Install Trivy Scanner
      run: |
        sudo apt-get update -y
        sudo apt-get install -y wget
        wget https://github.com/aquasecurity/trivy/releases/download/v0.50.1/trivy_0.50.1_Linux-64bit.deb
        sudo dpkg -i trivy_0.50.1_Linux-64bit.deb

    - name: Run Security Scan on Project Folder
      run: trivy fs .

